### PR TITLE
[FIX]: Add Sub boards

### LINKED ISSUE #273: [FIX]: Unhandled Runtime error when is not possible to add more sub-boards
### Steps to reproduce

1 - Create a new board
2 - Press ``+`` button until the error appears.

Screenshot 2022-06-27 at 18 28 18

Screenshot 2022-06-27 at 18 28 55

### PR DESCRIPTION
**Pull request by dvpfran**
Fixes #273 

## Proposed Changes
Fix ``canAdd`` function to disable button when is not possible to add more sub-boards

This pull request closes #273

### CODE REVIEW

File: frontend/src/hooks/useCreateBoard.tsx [hunk 1]
```diff
@@ -69,7 +69,7 @@ const useCreateBoard = (team: Team, stakeHolders: string[]) => {
 				});
 			}
 		},
-		[generateSubBoard]
+		[generateSubBoard, team]
```
Comment (dvpfran) [inline frontend/src/hooks/useCreateBoard.tsx:72]: Fix error:
``72:3  error    React Hook useCallback has a missing dependency: 'team'. Either include it or remove the dependency array  react-hooks/exhaustive-deps``

File: frontend/src/hooks/useCreateBoard.tsx [hunk 2]
```diff
@@ -97,6 +97,10 @@ const useCreateBoard = (team: Team, stakeHolders: string[]) => {
 	);
 
 	const canAdd = useMemo(() => {
+		if (dividedBoardsCount === teamMembers.length) {
+			return false;
+		}
+
 		if (dividedBoardsCount === Math.floor(teamMembers.length / 2)) {
 			return false;
 		}
```
Comment (dsousa12) [inline frontend/src/hooks/useCreateBoard.tsx:106]: Why not make the two conditions in one if, something like:
```suggestion
		if ((dividedBoardsCount === teamMembers.length) || (dividedBoardsCount === Math.floor(teamMembers.length / 2))) {
			return false;
		}
```

**Review by dsousa12 — CHANGES_REQUESTED** [review]
