### PR TITLE
fix: team members list ordering

### LINKED ISSUE #838: [BUG]: team members list ordering
## Description

When adding / removing members from a team, the list of users should come alphabetically ordered from the **backend**.

The **frontend** should be responsible for ordering the list by check state (members in the team should be displayed first).
When unchecking, the list should be reordered alphabetically.

image

### Steps to reproduce

Create a new team, and then add some members.
The member list isn't ordered by default.

### Expected result

The member list should be ordered by:
 - Members in the team first
 - Alphabetically after that

### Actual result

The member list isn't ordered before the "portal" is closed.

### PR DESCRIPTION
**Pull request by StereoPT**
Relates to #838 
Fixes #838 

## Screenshots

image

## Proposed Changes

  - The ListMembersDialog is now an independent component, it doesn't matter how he gets the users.
  - The component will sort the list it receives by:
    - Alphabetically
    - By Checked
    - Team Admin always on the first position 
  - getAllUsers from Backend will return an ordered list of users.

This pull request closes #838

### CODE REVIEW

File: backend/src/modules/users/utils/sortings.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import User from '../entities/user.schema';
+
+export const sortAlphabetically = (a: User, b: User) => {
+	if (a.firstName === b.firstName) {
+		return a.lastName < b.lastName ? -1 : 1;
+	}
+
+	return a.firstName < b.firstName ? -1 : 1;
+};
```
Comment (nunocaseiro) [inline backend/src/modules/users/utils/sortings.ts:9]: This should be sorted in the query using the mongoose sort method

File: backend/src/modules/users/services/get.user.service.ts [hunk 2]
```diff
@@ -38,8 +39,15 @@ export default class GetUserServiceImpl implements GetUserService {
 		return this.userRepository.countDocuments();
 	}
 
-	getAllUsers() {
-		return this.userRepository.findAll({ password: 0, currentHashedRefreshToken: 0 });
+	async getAllUsers() {
+		const allUsers = await this.userRepository.findAll({
+			password: 0,
+			currentHashedRefreshToken: 0
+		});
```
Comment (nunocaseiro) [inline backend/src/modules/users/services/get.user.service.ts:46]: The sort should be done in this query using the mongoose `sort` method.

[https://mongoosejs.com/docs/api/query.html#query_Query-sort](https://mongoosejs.com/docs/api/query.html#query_Query-sort)

**Review by nunocaseiro — CHANGES_REQUESTED** [review]

File: backend/src/modules/users/utils/sortings.ts (hunk 1 above)
Comment (StereoPT) [reply backend/src/modules/users/utils/sortings.ts:9]: We were reusing a method that was already being used.

File: backend/src/modules/users/services/get.user.service.ts [hunk 3]
```diff
@@ -38,8 +39,16 @@ export default class GetUserServiceImpl implements GetUserService {
...
+	async getAllUsers() {
+		const allUsers = await this.userRepository.findAll(
+			{
+				password: 0,
+				currentHashedRefreshToken: 0
+			},
+			{ firstName: 'asc', lastName: 'asc' }
+		);
+
+		return allUsers;
```
Comment (rpvsilva) [inline backend/src/modules/users/services/get.user.service.ts:51]:
```suggestion
	getAllUsers() {
		return this.userRepository.findAll(
			{
				password: 0,
				currentHashedRefreshToken: 0
			},
			{ firstName: 'asc', lastName: 'asc' }
		);
```

File: backend/src/modules/users/services/get.user.service.ts [hunk 4]
```diff
@@ -71,13 +80,7 @@ export default class GetUserServiceImpl implements GetUserService {
...
 		};
 
-		results.userWithTeams.sort((a, b) => {
-			if (a.user.firstName === b.user.firstName) {
-				return a.user.lastName < b.user.lastName ? -1 : 1;
-			}
-
-			return a.user.firstName < b.user.firstName ? -1 : 1;
-		});
+		results.userWithTeams.sort((a, b) => sortAlphabetically(a.user, b.user));
```
Comment (rpvsilva) [inline backend/src/modules/users/services/get.user.service.ts:83]: Now you can remove this, right?

File: backend/src/modules/users/utils/sortings.ts (hunk 1 above)
Comment (rpvsilva) [inline backend/src/modules/users/utils/sortings.ts:9]: Also this

**Review by rpvsilva — CHANGES_REQUESTED** [review]

File: backend/src/modules/users/services/get.user.service.ts (hunk 4 above)
Comment (StereoPT) [reply backend/src/modules/users/services/get.user.service.ts:81]: No, that needs to stay, because it's not an operation on the database, but on a joined array.

**Review by rpvsilva — DISMISSED** [review]

File: backend/src/modules/users/services/get.user.service.ts [hunk 5]
```diff
@@ -38,8 +39,14 @@ export default class GetUserServiceImpl implements GetUserService {
...
-	getAllUsers() {
-		return this.userRepository.findAll({ password: 0, currentHashedRefreshToken: 0 });
+	async getAllUsers() {
+		return await this.userRepository.findAll(
+			{
+				password: 0,
+				currentHashedRefreshToken: 0
+			},
+			{ firstName: 'asc', lastName: 'asc' }
+		);
```
Comment (nunocaseiro) [inline backend/src/modules/users/services/get.user.service.ts:49]:
```suggestion
 getAllUsers() {
		return this.userRepository.findAll(
			{
				password: 0,
				currentHashedRefreshToken: 0
			},
			{ firstName: 'asc', lastName: 'asc' }
		);
```

**Review by nunocaseiro — CHANGES_REQUESTED** [review]

**Review by rpvsilva — APPROVED** [review]

**Review by nunocaseiro — APPROVED** [review]

**Comment by nunocaseiro** [comment]
@all-contributors please add @StereoPT for code and doces

**Comment by nunocaseiro** [comment]
@all-contributors please add @JoaoSaIvador for code and docs
