### PR TITLE
fix: bug login page design and bugs

### LINKED ISSUE #890: [BUG]: login page design and bugs
## Description

 - When logging in with invalid credentials we get a non-descriptive error message. And the position is also wrong
 - The Image has no Shadow (as seen in the design document)
 - The Password Input has a black icon instead of dark gray
image

### Expected result

image

### PR DESCRIPTION
**Pull request by JoaoSaIvador**
Relates to #890 
Fixes #890

## Screenshots (if visual changes)

image

## Proposed Changes

- When logging in with invalid credentials we get the proper error message
- The Image has a Shadow
- The Password Input a dark gray icon

This pull request closes #890

### CODE REVIEW

File: frontend/src/components/Primitives/Input.tsx [hunk 1]
```diff
@@ -235,7 +235,7 @@ const Input: React.FC<InputProps> = ({
   const isValueEmpty = isEmpty(value);
 
   const autoState = useMemo(() => {
-    if (message) return 'error';
+    if (Object.keys(errors).length > 0 || message) return 'error';
```
Comment (mourabraz) [inline frontend/src/components/Primitives/Input.tsx:238]: Since `message` value depends on the `error`, it will be truthy only when `Object.keys(errors).length > 0` is truthy as well, considering own properties of the object, in that case it can be removed.

**Review by nunocaseiro — APPROVED** [review]
