### PR TITLE
fix: new line of the default text

### LINKED ISSUE #1101: [BUG]: text area template
## Description

In a text area that has two lines separated by a `/n`, the separator is dismissed when the user starts writing 

### Actual result

https://user-images.githubusercontent.com/90208434/219633213-99be5dde-5f6a-4a51-a427-6471e53d3d96.mov

### PR DESCRIPTION
**Pull request by nunocaseiro**
Fixes #1101 

## Proposed Changes

  - The "\n" remains when the user starts typing 
  - Change the text area to be a controlled component

This pull request closes #1101

### CODE REVIEW

File: frontend/src/components/Primitives/TextArea.tsx [hunk 1]
```diff
@@ -96,45 +96,52 @@ const TextArea: React.FC<ResizableTextAreaProps> = ({ id, placeholder, disabled,
...
+  const isValueEmpty = isEmpty(currentValue);
 
   const getCurrentState = useMemo(() => {
     if (errors[id]) return 'error';
     if (!dirtyFields[id]) return 'default';
     if (!isValueEmpty) return 'valid';
 
     return 'default';
-  }, [errors[id], dirtyFields[id], isValueEmpty]);
+  }, [dirtyFields, errors, id, isValueEmpty]);
```
Comment (JoaoSaIvador) [inline frontend/src/components/Primitives/TextArea.tsx]: `  }, [dirtyFields[id], errors[id], id, isValueEmpty]);`

Object comparisons return always false, even if their contents are the same. So, for the validations to update you need to specify the id of the form input.

**Review by JoaoSaIvador — APPROVED** [review]
