### PR TITLE
[FIX]: Avatar color

### LINKED ISSUE #260: [FIX]: Avatar color
## Summary
The avatar color are always changing.

### Basic example
First reload:
Screenshot 2022-06-24 at 17 14 01

Second reload:
Screenshot 2022-06-24 at 17 14 52

Third reload: 
Screenshot 2022-06-24 at 17 15 29

# Motivation 
Don't confuse users.

### PR DESCRIPTION
**Pull request by dvpfran**
Fixes #260 

## Screenshots (if visual changes)
- Dashboard page: First load
Screenshot 2022-06-29 at 10 27 37

- Dashboard page: second load
Screenshot 2022-06-29 at 10 28 43

- Boards page: First load
Screenshot 2022-06-29 at 10 30 29

- Boards page: Second load
Screenshot 2022-06-29 at 10 31 04

Proposed Changes
  - Colors of each user are being saved to Local Storage
  - Show the same colors every time the page is loaded

This pull request closes #260

### CODE REVIEW

File: frontend/src/components/Board/Card/CardFooter.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ import { BoardUser } from 'types/board/board.user';
 import CardType from 'types/card/card';
 import { CardItemType } from 'types/card/cardItem';
 import CommentType from 'types/comment/comment';
-import { getRandomColor } from 'utils/initialNames';
+import useAvatarColor from '../../../hooks/useAvatarColor';
```
Comment (dsousa12) [inline frontend/src/components/Board/Card/CardFooter.tsx:16]: Please remove `../../../`.

**Why***
- On `tsconfig.json` the `baseUrl` is setted to `src/` folder, spefically to avoid that.

File: frontend/src/components/Board/Card/CardFooter.tsx [hunk 2]
```diff
@@ -121,17 +121,17 @@ const CardFooter = React.memo<FooterProps>(
 			});
 		};
 
-		const color = useMemo(() => {
-			return getRandomColor();
-		}, []);
+		const GetAvatarColor = (id: string | undefined) => {
```
Comment (dsousa12) [inline frontend/src/components/Board/Card/CardFooter.tsx:124]: Use lower case on first letter (`G`), is not a component, so please use camel case.

File: frontend/src/components/CardBoard/CardAvatars.tsx [hunk 3]
```diff
@@ -79,55 +72,58 @@ const CardAvatars = React.memo<CardAvatarProps>(
...
 		);
 
-		const colors = useMemo(() => {
-			const col = [];
-			for (let i = 0; i < 3; i++) {
-				col.push(stakeholders ? stakeholdersColors : getRandomColor());
-			}
-			return col;
-		}, [getRandomColor, stakeholdersColors, stakeholders]);
+		const GetAvatarColor = (value: User | string) => {
```
Comment (dsousa12) [inline frontend/src/components/CardBoard/CardAvatars.tsx:75]: Sama here

File: frontend/src/components/CardBoard/CardAvatars.tsx [hunk 4]
```diff
@@ -79,55 +72,58 @@ const CardAvatars = React.memo<CardAvatarProps>(
...
+			}
+			const initials = `${value.firstName[0]}${value.lastName[0]}`;
+			return (
+				<Tooltip
+					key={`${value}-${idx}-${Math.random()}`}
+					content={`${value.firstName} ${value.lastName}`}
+				>
+					<div>
 						<Avatar
-							key={`${value}-${idx}-${Math.random()}`}
```
Comment (dsousa12) [inline frontend/src/components/CardBoard/CardAvatars.tsx:95]: Why remove the `key`?
When you have a `.map` or a loop, **React** needs a `key` for each element.


In this case, you have the map on line 113 and 121.

**Review by dsousa12 — CHANGES_REQUESTED** [review]

**Review by dsousa12 — APPROVED** [review]
LGTM 🚀
