### PR TITLE
[REFACTOR]: fix card team

### LINKED ISSUE #573: [REFACTOR]: fix card team
## Summary

The card team has the count of boards coming from the dashboard. This needs to be changed to just count the boards of each team. The layout also needs to be fixed.

### PR DESCRIPTION
**Pull request by CatiaAntunes96**
Relates to #573 

## Proposed Changes

  - Layout of card team fixed
  - Add boardsCount attribute and logic to backend
  - Display boards count by teams on each card team

This pull request closes #573

### CODE REVIEW

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx [hunk 1]
```diff
@@ -29,10 +24,10 @@ const BoardsInfo = ({ userSAdmin, teamAdmin }: BoardsInfoProps) => {
 									css={{
 										width: '16px',
 										height: '$32',
-										marginRight: '$10'
+										marginRight: '5px'
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx:27]: Can you replace the `px` with the token?

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx [hunk 2]
```diff
@@ -29,10 +24,10 @@ const BoardsInfo = ({ userSAdmin, teamAdmin }: BoardsInfoProps) => {
...
 									}}
 								/>
-								<Text css={{ ml: '$14' }} size="sm" weight="medium">
+								<Text css={{ ml: '5px' }} size="sm" weight="medium">
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx:30]: Same as above

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx [hunk 3]
```diff
@@ -48,35 +48,35 @@ const CardBody = React.memo<CardBodyProps>(({ userId, team }) => {
...
+					py: '$22',
+					maxHeight: '$76',
+					ml: 0
+				}}
+			>
+				<Flex align="center" css={{ width: '25%' }} gap="8">
+					<Icon
+						name="blob-team"
+						css={{
+							width: '32px',
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx:67]:
```suggestion
							width: '$32',
```

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx [hunk 4]
```diff
@@ -29,10 +24,10 @@ const BoardsInfo = ({ userSAdmin, teamAdmin }: BoardsInfoProps) => {
 									css={{
 										width: '16px',
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx:25]:
```suggestion
										width: $16,
```
Please verify if this token exists otherwise is good to have it

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx [hunk 5]
```diff
@@ -48,35 +48,35 @@ const CardBody = React.memo<CardBodyProps>(({ userId, team }) => {
...
-							<CardTitle teamId={id} title={team.name} />
-						</Flex>
+					<Flex align="center" gap="8">
+						<CardTitle teamId={id} title={team.name} />
 					</Flex>
+				</Flex>
 
-					<Flex align="center" css={{ justifyContent: 'center', width: '100%' }} gap="8">
+				<Flex align="center" css={{ justifyContent: 'start', width: '683' }} gap="8">
+					<Flex align="center" css={{ width: '147px' }}>
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx:79]: I know this width values won't be used very often but for consistency, we should use tokens

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx [hunk 6]
```diff
@@ -112,26 +113,35 @@ const CardBody = React.memo<CardBodyProps>(({ userId, team }) => {
...
+						<Separator
+							orientation="vertical"
+							css={{
+								ml: '$40',
+								backgroundColor: '$primary100',
+								height: '$24 !important'
+							}}
+						/>
+
+						<Flex align="center" css={{ width: '237px' }} justify="start">
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx:126]:
```suggestion
						<Flex align="center" css={{ width: $237 }} justify="start">
```

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx [hunk 7]
```diff
@@ -87,22 +87,23 @@ const CardBody = React.memo<CardBodyProps>(({ userId, team }) => {
...
-							gap="8"
-						>
-							<Text color="primary300" size="sm">
+					<Flex
+						align="center"
+						css={{ ml: '$40', display: 'flex', alignItems: 'center' }}
+						gap="8"
+					>
+						<Flex align="center" css={{ width: '127px' }}>
+							<Text color="primary300" css={{ mr: '2px' }} size="sm">
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/CardBody.tsx:106]: Missing tokens

File: frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx [hunk 8]
```diff
@@ -1,25 +1,20 @@
...
-		enabled: true,
-		refetchOnWindowFocus: false
-	});
-
-	if (!boardInfo?.boardsCount) {
+const BoardsInfo = ({ userSAdmin, teamAdmin, team }: BoardsInfoProps) => {
+	if (team.boardsCount === 0) {
 		return (
-			<Flex css={{ ml: '$40', display: 'flex', alignItems: 'center' }}>
+			<Flex css={{ ml: '$20', display: 'flex', alignItems: 'center' }}>
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx:17]:
```suggestion
			<Flex css={{ ml: '$20', alignItems: 'center' }}>
```
The styled `flex` already has the `display: 'flex'`

**Review by nunocaseiro — CHANGES_REQUESTED** [review]

File: frontend/src/pages/teams/new.tsx [hunk 9]
```diff
@@ -35,23 +35,25 @@ const NewTeam: NextPage = () => {
...
+						role: TeamUserRoles.ADMIN,
+						isNewJoiner: false
+					});
+				}
+			});
 
-		const usersWithChecked = data?.map((user) => {
-			return { ...user, isChecked: user._id === session?.user.id };
-		});
+			const usersWithChecked = data?.map((user) => {
```
Comment (mourabraz) [inline frontend/src/pages/teams/new.tsx:49]: "data" exists inside the "if" statement, I would remove the "?" from "data".
Maybe I would check if "data" is an Array stead if it is truthy.  
```suggestion
			if(Array.isArray(data)) {
```

**Review by mourabraz — APPROVED** [review]
LGTM 🚀
