### PR TITLE
[FIX]: Responsible Lottery is freezing the page when the group only contains 1 user.

### LINKED ISSUE #272: [FIX]: Responsible Lottery is freezing the page when the group only contains 1 user.
### Steps to reproduce

1. Create a new board
2. Click ``Responsible Lottery`` button in a group with only one member.

Screenshot 2022-06-27 at 17 43 43

Should we automatically define the user as responsible when the group contains only one member? And disable or hide the button in these cases.

### PR DESCRIPTION
**Pull request by joaosantos99**
Fixes #272 

## Screenshots (if visual changes)

Screenshot 2022-06-28 at 15 47 50

## Proposed Changes

  - Blocking the function to change the responsible if the board as only 1 or less members
  - Added a disable state to the button
  
This pull request closes #272

### CODE REVIEW

File: frontend/src/components/CreateBoard/SubTeamsTab/SubCardBoard.tsx [hunk 1]
```diff
@@ -84,34 +86,59 @@ const SubCardBoard: React.FC<SubCardBoardProps> = ({ board, index, setBoard }) =
...
-								}
-							}}
-							align="center"
-							justify="center"
-							onClick={handleLottery}
-						>
-							<Icon
-								name="wand"
+						{users.length <= 1 ? (
+							<Flex
```
Comment (dsousa12) [inline frontend/src/components/CreateBoard/SubTeamsTab/SubCardBoard.tsx:90]: Please make sure you use the same style (if match with design of course)

File: frontend/src/components/CreateBoard/SubTeamsTab/SubCardBoard.tsx [hunk 2]
```diff
@@ -84,34 +86,59 @@ const SubCardBoard: React.FC<SubCardBoardProps> = ({ board, index, setBoard }) =
...
+								css={{
+									height: '$24',
+									width: '$24',
+									borderRadius: '$round',
+									border: '1px solid $colors$primary400',
+									ml: '$12',
+									cursor: 'pointer',
+
+									transtion: 'all 0.2s ease-in-out',
```
Comment (dsousa12) [inline frontend/src/components/CreateBoard/SubTeamsTab/SubCardBoard.tsx:121]: Please change `transtion` for `transition`

**Review by dsousa12 — CHANGES_REQUESTED** [review]

**Review by dsousa12 — APPROVED** [review]
LGTM 🚀
