### PR TITLE
[BUG]: Team configuration is reseted when clicking on configurations and coming back to it

### LINKED ISSUE #350: [BUG]: Team configuration is reset when clicking configurations and coming back to it
## Description

When creating a split board, clicking on **Configurations** and then going back to **Team/-Sub-teams configurations** resets the teams

Screenshot 2022-07-22 at 13 58 03

### Steps to reproduce

* Setup teams on the **Team/-Sub-teams configurations**
* Click on **Configurations**
* Click back on **Team/-Sub-teams configurations**

### Expected result

Team configuration should remain the same

### Actual result

The configuration is lost

### PR DESCRIPTION
**Pull request by joaosantos99**
Fixes #350

## Proposed Changes

  - Created a state for identifying when the sub-boards don't need to be reset.

This pull request closes #350

### CODE REVIEW

File: frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx [hunk 1]
```diff
@@ -57,6 +58,7 @@ const MainBoardCard = React.memo(({ team }: MainBoardCardInterface) => {
 	 * Recoil Atoms
 	 */
 	const haveError = useRecoilValue(createBoardError);
+	const [newBoard, setNewBoard] = useRecoilState(newBoardState);
```
Comment (dsousa12) [inline frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx:61]: Why you need a new **Recoil** state to storage a boolean?

**Review by dsousa12 — CHANGES_REQUESTED** [review]

File: frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx (hunk 1 above)
Comment (joaosantos99) [reply frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx:61]: Because when the user changes from the teams configuration to the board configuration and switch back again to the teams configuration, it re-renders the component and in the useEffect resets any change on the teams. So i added a booleon to know when to reset the teams cahnges.

Comment (dsousa12) [reply frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx:61]: Ok, but you can't avoid the re-renders without another state?

Comment (dsousa12) [reply frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx:61]: If not, maybe create a normal `useState` and send by props the `set` function.
Because you don't use this recoil state in other places I think.

But wait for other reviews.

Comment (joaosantos99) [reply frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx:61]: I initially i used `useState`, but later i needed a way to reset the state when someone clicked on the "Add new board" button so i switched to the atom.
Do you have any suggestion to solve that problem?

**Review by dsousa12 — DISMISSED** [review]
LGTM 🚀

**Review by dsousa12 — APPROVED** [review]
