### PR TITLE
fix: unmerge, avoid requesting on success, handle erros

### LINKED ISSUE #835: [BUG]: unmerge and some crashes
## Description

All users can merge but not everyone can unmerge the cards.
Some crashes are happening when multiple people are making operations on a board

### PR DESCRIPTION
**Pull request by nunocaseiro**
Fixes #835 

## Proposed Changes

  - Unmerge is now available to everyone 
  - Try to handle some crashes
  - Reduce the board requests on success

This pull request closes #835

### CODE REVIEW

**Review by rpvsilva — APPROVED** [review]

File: backend/src/modules/boards/utils/populate-board.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
+export const BoardDataPopulate = [
```
Comment (rpvsilva) [inline backend/src/modules/boards/utils/populate-board.ts:1]: Can you type this const?

**Review by rpvsilva — CHANGES_REQUESTED** [review]

**Review by rpvsilva — APPROVED** [review]
