### PR TITLE
fix: new board shows team selected on 1st render

### LINKED ISSUE #745: [BUG]: First render doesnt show team
## Description

When user tries to create the first team board through the teams page, the 1st render of the page doesn't show the team selected.

### Steps to reproduce

1. Go to teams Page.
2. Click on "Create first team board".
3. Click on "SPLIT retro".

### Expected result

The user should see the team selected on the board creation.

### Actual result

No team appears.

### PR DESCRIPTION
**Pull request by patricia-mdias**
Fixes #745 

## Proposed Changes

  - New board shows team on 1st render when user clicks on "Create first team board" of a team.

This pull request closes #745

### CODE REVIEW

File: frontend/src/pages/boards/newSplitBoard.tsx [hunk 1]
```diff
@@ -125,6 +127,11 @@ const NewSplitBoard: NextPage = () => {
     name: 'text',
   });
 
+  if (routerTeam && !selectedTeam) {
+    const foundTeam = teams.find((team) => team._id === routerTeam);
+    setSelectedTeam(foundTeam);
+  }
```
Comment (nunocaseiro) [inline frontend/src/pages/boards/newSplitBoard.tsx:133]: This code will be executed in every render. can you move this to an useEffect ?

**Review by nunocaseiro — CHANGES_REQUESTED** [review]

File: frontend/src/pages/boards/newSplitBoard.tsx (hunk 1 above)
Comment (patricia-mdias) [reply frontend/src/pages/boards/newSplitBoard.tsx:133]: If I move this code to an useEffect, the problem will still persist. Using useEffect, there's no team selected on the 1st render.

Comment (nunocaseiro) [reply frontend/src/pages/boards/newSplitBoard.tsx:133]: Wierd. But ok lets go on with this

**Review by nunocaseiro — APPROVED** [review]
