### PR TITLE
[BUG]: Lazy loading indicator in the dashboard

### LINKED ISSUE #358: [BUG]: Lazy loading indicator in the dashboard
## Description

In the dashboard screen, when the the user scrolls down the boards list and the lazy loading is triggered, a loading screen is shown in the whole page. It should be like an activity indicator on the bottom of the scroll list

### PR DESCRIPTION
**Pull request by joaosantos99**
Fixes #358

## Screenshots (if visual changes)

Screenshot 2022-07-25 at 10 36 46

## Proposed Changes

  - Change the pageLoading component for the dotsLoading component
  - Giving z-index to pageLoading to fix the overlap bug
 

This pull request closes #358

### CODE REVIEW

File: frontend/src/components/loadings/LoadingPage/styles.tsx [hunk 1]
```diff
@@ -8,6 +8,7 @@ const Overlay = styled('div', Flex, {
 	right: 0,
 	bottom: 0,
 	left: 0,
+	zIndex: 10,
```
Comment (dsousa12) [inline frontend/src/components/loadings/LoadingPage/styles.tsx:11]: Why you need to change `zIndex` of this component?

**Review by dsousa12 — CHANGES_REQUESTED** [review]

File: frontend/src/components/loadings/LoadingPage/styles.tsx (hunk 1 above)
Comment (joaosantos99) [reply frontend/src/components/loadings/LoadingPage/styles.tsx:11]: Yes, is to correct this bug

Screenshot 2022-07-26 at 09 38 26

**Review by dsousa12 — APPROVED** [review]
