### PR TITLE
fix: multiple bugs

### LINKED ISSUE #781: [BUG]: As a normal user, I see the add/remove members button, on a Team
## Description

As a normal user, when I go to a certain team's page, I see the button to add/remove members, but thats a Super Admin and Team Admin feature

### Steps to reproduce

Teams -> select a team -> button "add/remove members" is shown

### Expected result

There should not be any button

### Actual result
image

There's a button to add/remove members

### LINKED ISSUE #782: [BUG]: Team member has option to change role
## Description
As a team member the user has the option (dropdown) to change his role. It's only frontend bug because when choosing other role it gives 403 forbidden.

### Steps to reproduce

On team members page of a logged user (member), the user has the option to change is role on that team.

### Expected result

Not being able to click on the change role dropdown.

### Actual result

The user is able to click on the change role option.

### PR DESCRIPTION
**Pull request by RafaelSBatista97**
#782 and #781

Fixes #782 and #781

## Proposed Changes

  - Only users with privileges (isSAdmin, stakeholder, team admin) can change the roles of teams. Members are not allowed.
  - Remove button "add/remove member" when is team member.
  - Change Popup message when adding teams to user.
  

@GuiSanto 

This pull request closes #781 and #782

### CODE REVIEW

File: frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx [hunk 1]
```diff
@@ -89,25 +88,23 @@ const PopoverRoleSettings: React.FC<PopoverRoleSettingsProps> = React.memo(
...
-                </PopoverItemStyled>
-              </PopoverCloseStyled>
-            )}
+            <PopoverCloseStyled>
+              <PopoverItemStyled
+                align="end"
+                direction="column"
+                onClick={() => {
+                  handleSelectFunction(TeamUserRoles.MEMBER);
+                }}
```
Comment (nunocaseiro) [inline frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx:97]:
```suggestion
                onClick={handleSelectFunction(TeamUserRoles.MEMBER)}
```

**Review by nunocaseiro — DISMISSED** [review]
LGTM 🚀

**Review by nunocaseiro — APPROVED** [review]
