### PR TITLE
[FIX]: "Your teams" blob displaced in google chrome

### LINKED ISSUE #247: [FIX]: "Your teams" blob displaced in google chrome
## Summary

Blob from "your teams" card displaced at the top in google chrome

### Basic example

Screenshot 2022-06-23 at 15 08 28

### Motivation

Consistency across browsers

### PR DESCRIPTION
**Pull request by joaosantos99**
Fixes #247 

## Screenshots (if visual changes)

Screenshot 2022-06-23 at 15 16 12

## Proposed Changes

  - The position of the "your teams" blob on chrome

This pull request closes #247

### CODE REVIEW

File: frontend/src/components/Dashboard/Tiles/index.tsx [hunk 1]
```diff
@@ -39,9 +39,9 @@ const Index: React.FC<TilesProps> = ({ data }) => {
 					css={{
 						position: 'absolute',
 						right: '-1px',
-						top: '-5px',
+						top: '0px',
 						width: '126px',
-						height: '$100'
+						height: '90px'
```
Comment (dsousa12) [inline frontend/src/components/Dashboard/Tiles/index.tsx:44]: Please create the `90px` size on the **Stitches** configs (`styles/stitches/partials/sizes.ts`) and use it (`$90`)

**Review by dsousa12 — CHANGES_REQUESTED** [review]

**Review by dsousa12 — APPROVED** [review]

**Comment by dsousa12** [comment]
@all-contributors please add @joaosantos99  as contributor for code and docs
